### PR TITLE
Lexington!

### PR DESCRIPTION
**Pull request by chaserx**
add Lexington, KY to where.geojson

### CODE REVIEW

**Comment by chaserx** [comment]
looks like my sublime prefs have removed some whitespace too.

**Comment by boonrs** [comment]
Could you remove the white space commit? Otherwise, looks good. Welcome Lexington!

**Comment by chaserx** [comment]
@boonrs should be all fixed up. thanks!

**Comment by boonrs** [comment]
Hurray for Lexington pets!

**Pull request merged**
